In [1]:
import numpy as np
import pandas as pd

In [5]:
adult = pd.read_csv("Downloads/Chrome Downloads/adult_num.csv")

In [7]:
x = adult.iloc[:, :-1]
y = adult.iloc[:,-1].values

# BAGGING

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state = 0)

In [20]:
#import bagging
from sklearn.ensemble import BaggingClassifier

#import classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

#initialise classifier - the default is decision tree
BC = BaggingClassifier(n_estimators=10, random_state= 0)

#fit the classifier to the data
BC.fit(x_train, y_train)

#predict the values for the test set
y_pred = BC.predict(x_test)

#performance metrics
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

print(confusion_matrix(y_test, y_pred), '\n')
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)), '\n')

print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_pred))

[[5750  409]
 [ 853 1129]] 

Mean Absolute Error: 0.15501781107971993
Mean Squared Error: 0.15501781107971993
Root Mean Squared Error: 0.39372301314467245 

              precision    recall  f1-score   support

           0       0.87      0.93      0.90      6159
           1       0.73      0.57      0.64      1982

    accuracy                           0.84      8141
   macro avg       0.80      0.75      0.77      8141
weighted avg       0.84      0.84      0.84      8141

Accuracy: 0.8449821889202801
AUC: 0.7516098777616834


# RANDOM FOREST

In [23]:
from sklearn.ensemble import RandomForestClassifier

#initialise classifier

RF = RandomForestClassifier(random_state = 0)

#fit classifier
RF.fit(x_train, y_train)

#predict 
y_pred = RF.predict(x_test)

#performance metrics

print(confusion_matrix(y_test, y_pred), '\n')
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)), '\n')

print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_pred))

[[5736  423]
 [ 760 1222]] 

Mean Absolute Error: 0.14531384350816853
Mean Squared Error: 0.14531384350816853
Root Mean Squared Error: 0.3812005292600845 

              precision    recall  f1-score   support

           0       0.88      0.93      0.91      6159
           1       0.74      0.62      0.67      1982

    accuracy                           0.85      8141
   macro avg       0.81      0.77      0.79      8141
weighted avg       0.85      0.85      0.85      8141

Accuracy: 0.8546861564918314
AUC: 0.77393447997393


# BOOSTING

In [26]:
from sklearn.ensemble import AdaBoostClassifier

#initialise
AB = AdaBoostClassifier(n_estimators = 100, random_state = 0) #n_estimators is the number of weak learners to train

#fit
AB.fit(x_train, y_train)

#predict
y_pred = AB.predict(x_test)

#performance
print(confusion_matrix(y_test, y_pred), '\n')
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)), '\n')

print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_pred))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


[[5774  385]
 [ 746 1236]] 

Mean Absolute Error: 0.13892642181550177
Mean Squared Error: 0.13892642181550177
Root Mean Squared Error: 0.37272834855361053 

              precision    recall  f1-score   support

           0       0.89      0.94      0.91      6159
           1       0.76      0.62      0.69      1982

    accuracy                           0.86      8141
   macro avg       0.82      0.78      0.80      8141
weighted avg       0.86      0.86      0.86      8141

Accuracy: 0.8610735781844983
AUC: 0.7805511824311316
